### ISSUE TITLE
[Bug]: my-slider-v2 allowTapping false not working

### ISSUE THREAD

**Issue by L-E-0-N** [AnthonMS/my-cards#49]
### Current Behavior

When setting the value 'allowTapping' to 'false' it's won't function at all. Neither by tapping (makes sense) but also not by dragging the thumb which is wanted. There is no way to adjust the slider.

### Expected Behavior

To only be able to change the value by dragging the thumb.

### Steps To Reproduce

1. Create a new my-slider-v2 card
2. Use some basic version:
```type: custom:my-slider-v2
entity: light.tafellamp_groep
allowTapping: false
styles:
  card:
    - height: 50px
```
3. Try changing the value by dragging the thumb, it's not working

### Environment

```markdown
- OS: Intel Nuc Generic x86-64
- Browser: MacOS Chrome / Home Assistant iOS companion app
- Version: Mybundle v1.0.2
- Hassio: 2023.6.2
```

**Comment by AnthonMS** [comment]
No I have stumpled upon this lately as well. I will try to take a look at it soon.

**Comment by DANIELlOlL** [comment]
I also experienced this problem, cause i wanted to turn off Tapping, so that I can scroll trough my Dashboard without turning any lights on or off. Did you find a solution for this Problem?

**Comment by AnthonMS** [comment]
This should be fixed in the latest release. Let me know if there are more issues.

**Comment by DANIELlOlL** [comment]
Yes :) it works thanks

**Comment by L-E-0-N** [comment]
> This should be fixed in the latest release. Let me know if there are more issues.

This is great! But to challenge it one step further. Now it’s still not possible to scroll when placing a finger on the slider and dragging vertical. Meaning when your dashboard has multiple slider, we still need to carefully place our finger to scroll up and down the dashboard. Ortherwise we’re scrolling within a slider and its not working. Do you think there could be a fix for that?
